name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: npm run setup

      - name: Init
        run: npm run init

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Doc
        run: npm run doc

      - name: Test
        run: npm run test

      - name: Examples
        run: npm run examples

# TODO: Run test.html in browser
